// Generates the pastel Tailwind palette block in src/index.css.
// Shades 50–500 are soft tints and fills; 600–950 stay deep enough to be read as text.
import fs from "node:fs";
const HUES = { red: 27, rose: 12, pink: 350, fuchsia: 322, purple: 304, violet: 292, indigo: 275, blue: 255, sky: 232, cyan: 212, teal: 185, emerald: 163, green: 148, lime: 128, yellow: 95, amber: 78, orange: 52 };
//            L      C
const SCALE = {
  50:  [0.978, 0.016], 100: [0.958, 0.032], 200: [0.925, 0.052], 300: [0.885, 0.072],
  400: [0.835, 0.088], 500: [0.775, 0.098], 600: [0.515, 0.085], 700: [0.455, 0.075],
  800: [0.395, 0.062], 900: [0.335, 0.050], 950: [0.27, 0.040],
};
let css = "\n/* ─── Pastel palette (generated by scripts/pastel-palette.mjs) ───\n   50–500 are soft tints and fills; 600+ are muted inks that stay readable. */\n@theme {\n";
for (const [name, h] of Object.entries(HUES))
  for (const [s, [l, c]] of Object.entries(SCALE)) css += `  --color-${name}-${s}: oklch(${l} ${c} ${h});\n`;
css += "}\n/* ─── end pastel palette ─── */\n";
const f = "src/index.css";
let src = fs.readFileSync(f, "utf8").replace(/\n\/\* ─── Pastel palette[\s\S]*?end pastel palette ─── \*\/\n/, "");
const anchor = src.indexOf("/* ─── LIGHT MODE");
src = src.slice(0, anchor) + css.trimStart() + "\n" + src.slice(anchor);

// Brand tokens → pastel. Fills get lighter; inks stay dark enough for text.
const tokens = {
  "--background: 42 30% 96%;": "--background: 40 45% 97%;",
  "--card: 42 44% 99%;": "--card: 40 60% 99%;",
  "--sidebar: 45 38% 94%;": "--sidebar: 38 55% 95%;",
  "--sidebar-primary: 46 88% 58%;": "--sidebar-primary: 47 90% 78%;",
  "--sidebar-accent: 48 62% 90%;": "--sidebar-accent: 45 80% 92%;",
  "--primary: 46 88% 58%;": "--primary: 47 90% 78%;",
  "--accent: 48 62% 90%;": "--accent: 45 80% 92%;",
  "--secondary: 40 20% 92%;": "--secondary: 260 35% 94%;",
  "--muted: 40 20% 93%;": "--muted: 38 30% 93%;",
  "--brand: 51 85% 74%;\n  --brand-ink: 40 82% 32%;\n  --brand-wash: 51 80% 94%;": "--brand: 50 90% 84%;\n  --brand-ink: 40 60% 32%;\n  --brand-wash: 50 85% 95%;",
  "--success: 152 62% 26%;": "--success: 155 38% 32%;",
  "--warning: 28 78% 31%;": "--warning: 25 55% 36%;",
  "--destructive: 9 64% 46%;": "--destructive: 5 52% 47%;",
  "--chart-1: 205 62% 24%;": "--chart-1: 210 60% 70%;",
  "--chart-2: 43 88% 39%;": "--chart-2: 42 85% 68%;",
  "--chart-3: 7 58% 43%;": "--chart-3: 8 70% 76%;",
  "--chart-4: 276 40% 50%;": "--chart-4: 272 45% 76%;",
  "--chart-5: 161 44% 42%;": "--chart-5: 158 42% 66%;",
  "--logo-accent: #F2C636;": "--logo-accent: #F4D56E;",
};
const missing = [];
for (const [a, b] of Object.entries(tokens)) { if (!src.includes(a)) missing.push(a.split(":")[0]); src = src.replace(a, b); }
fs.writeFileSync(f, src);
console.log("palette written; tokens not found:", missing.length ? missing : "none");
